import {Client} from '../../types/client';

const sampleClients: Client[] = [
  {
    id: '1',
    name: 'Pierre Martin',
    type: 'Acheteur',
    status: 'Actif',
    phone: '+33 6 12 34 56 78',
    email: 'pierre.martin@example.com',
    propertyType: 'Appartement',
    area: 'Maroc',
    secteur: 'Medina',
    minSurface: 80,
    surfaceMax: 120,
    rooms: '3',
    prixMin: 800000,
    prixMax: 1200000,
    devise: 'MAD',
    classification: 'Tres actif',
    statutMetier: 'En recherche',
    croisementAutomatique: true,
    categorie: 'Vente',
    piecesOperator: 'ge',
    pieces: 3,
    chambresOperator: 'ge',
    chambres: 2,
    vue: 'Mer',
    exposition: 'Sud',
    etat: 'Bon',
    standing: 'Moyen',
    disponibilite: 'Immediate',
    attributPrincipal: 'Residence secondaire',
    attributsPersonnalises: ['Piscine chauffee', 'Vue ocean', 'Suite parental'],
    criteres: ['Balcon', 'Parking', 'Terrasse', 'Piscine'],
    proximites: {
      transports: ['Aeroport', 'Bus', 'Taxi'],
      commerces: ['Centre ville', 'Supermarché'],
      education: ['Ecole primaire'],
      sante: ['Medecin'],
      loisirs: ['Mer', 'Plage'],
    },
    prestations: {
      exterieur: ['Portail electrique', 'Videophone', 'Cloture'],
      confort: ['Air conditionne', 'Double vitrage', 'Fibre optique'],
      electromenager: ['Lave-linge', 'Refrigerateur', 'Four'],
      multimedia: ['Internet', 'Teledistribution'],
      sport: [],
    },
    contribution: 300000,
    financingType: 'Pret bancaire',
    loanDuration: 20,
    capaciteEmprunt: 520000,
    currentSituation: 'Locataire',
    moveInDate: '2025-09-01',
    urgency: '3 mois',
    numeroMandat: 'MDR-2025-001',
    dateSignature: '2025-06-01',
    dateDebut: '2025-06-01',
    dateExpiration: '2025-12-01',
    statutMandat: 'Actif',
    typeMandat: 'Non-exclusif',
    conjoint: 'Sophie Martin',
    agentDesigne: 'agent-1',
    typeRemuneration: 'Commission sur prix achat',
    montantRemuneration: 36000,
    conditionPaiement: 'Vente definitive',
    dureeProtection: '3',
    notes: 'Client très motivé, cherche une résidence secondaire avec vue mer. Budget flexible si coup de coeur.',
    lastContact: '2025-06-15',
    events: [
      {
        id: 'event-1',
        type: 'email',
        date: '2025-06-15T10:00:00Z',
        summary: 'Premier contact par email',
        agent: 'John Doe'
      }
    ],
    documents: [
      { name: 'CIN - Pierre Martin.pdf', url: '#', type: 'identity', uploadedAt: '2025-06-01', category: 'identite', size: '2.1 Mo' },
      { name: 'Justificatif de domicile - Pierre Martin.pdf', url: '#', type: 'proof_address', uploadedAt: '2025-06-01', category: 'identite', size: '1.4 Mo' },
      { name: 'Fiches de paie - Pierre Martin (3 derniers mois).pdf', url: '#', type: 'payslip', uploadedAt: '2025-06-05', category: 'financier', size: '3.2 Mo' },
      { name: "Avis d'imposition 2025 - Pierre Martin.pdf", url: '#', type: 'tax_notice', uploadedAt: '2025-06-05', category: 'financier', size: '1.8 Mo' },
      { name: 'Mandat de recherche - Pierre Martin.pdf', url: '#', type: 'mandate_search', uploadedAt: '2025-06-01', category: 'mandat', size: '0.9 Mo' },
    ],
    createdAt: '2025-06-01',
    updatedAt: '2025-06-15',
    createdBy: 'system',
  },
  {
    id: '2',
    name: 'Marie Lambert',
    type: 'Acheteur',
    status: 'Actif',
    phone: '+33 6 98 76 54 32',
    email: 'marie.lambert@example.com',
    propertyType: 'Maison',
    area: 'Maroc',
    secteur: 'Ghazoua',
    minSurface: 100,
    surfaceMax: 150,
    rooms: '5',
    prixMin: 1500000,
    prixMax: 2200000,
    devise: 'MAD',
    classification: 'Actif',
    statutMetier: 'En negociation',
    categorie: 'Vente',
    pieces: 5,
    chambres: 3,
    vue: 'Jardin',
    exposition: 'Sud-Est',
    etat: 'Neuf',
    standing: 'Luxe',
    disponibilite: 'Flexible',
    attributPrincipal: 'Villegiature',
    criteres: ['Jardin', 'Garage', 'Piscine', 'Ascenseur'],
    proximites: {
      transports: ['Autoroute', 'Gare'],
      commerces: ['Commerces'],
      education: ['Ecole primaire', 'Ecole secondaire'],
      sante: ['Hopital / Clinique'],
      loisirs: ['Golf', 'Parc'],
    },
    prestations: {
      exterieur: ['Portail electrique', 'Video surveillance', 'Puits'],
      confort: ['Cheminee', 'Domotique', 'Piscine', 'Spa'],
      electromenager: ['Cuisiniere', 'Lave-vaisselle'],
      multimedia: ['Internet', 'Reseau informatique'],
      sport: [],
    },
    contribution: 500000,
    financingType: 'Pret bancaire',
    loanDuration: 25,
    currentSituation: 'Proprietaire',
    urgency: '6 mois',
    notes: 'Famille avec enfants, cherche une villa avec jardin et piscine. Secteur Ghazoua exclusivement.',
    lastContact: '2025-06-10',
    events: [],
    createdAt: '2025-05-15',
    updatedAt: '2025-06-10',
    createdBy: 'system',
  },
  {
    id: '4',
    name: 'Hassan El Fassi',
    type: 'Vendeur',
    status: 'Actif',
    phone: '+212 6 98 76 54 32',
    email: 'hassan.elfassi@example.com',
    propertyType: 'Villa',
    area: 'Maroc',
    secteur: 'Argana',
    minSurface: 200,
    surfaceMax: 300,
    rooms: '6',
    prixMin: 2500000,
    prixMax: 3500000,
    devise: 'MAD',
    classification: 'Actif',
    statutMetier: 'En mandat',
    croisementAutomatique: true,
    categorie: 'Vente',
    piecesOperator: 'ge',
    pieces: 6,
    chambresOperator: 'ge',
    chambres: 4,
    vue: 'Panoramique',
    exposition: 'Sud',
    etat: 'Tres bon',
    standing: 'Luxe',
    disponibilite: '3 mois',
    attributPrincipal: 'Selection',
    attributsPersonnalises: ['Piscine chauffee', 'Vue ocean', 'Pool house'],
    criteres: ['Jardin', 'Garage', 'Piscine', 'Terrasse', 'Parking'],
    proximites: {
      transports: ['Aeroport', 'Autoroute'],
      commerces: ['Centre ville', 'Supermarché'],
      education: ['Ecole primaire', 'Ecole secondaire'],
      sante: ['Hopital / Clinique', 'Medecin'],
      loisirs: ['Golf', 'Mer', 'Plage'],
    },
    prestations: {
      exterieur: ['Portail electrique', 'Video surveillance', 'Cloture', 'Eclairage exterieur'],
      confort: ['Air conditionne', 'Domotique', 'Piscine', 'Cheminee', 'Fibre optique'],
      electromenager: ['Cuisiniere', 'Lave-vaisselle', 'Refrigerateur'],
      multimedia: ['Internet', 'Teledistribution'],
      sport: [],
    },
    currentSituation: 'Proprietaire occupant',
    reasonForSelling: 'Mutation professionnelle - mutation vers Rabat pour un poste de direction',
    notes: 'Très belle villa avec piscine chauffée et vue panoramique. Propriétaire pressé par la mutation.',
    lastContact: '2026-06-01',
    numeroMandat: 'MV-2026-001',
    dateSignature: '2026-06-01',
    dateDebut: '2026-06-01',
    dateExpiration: '2026-09-01',
    statutMandat: 'Actif',
    typeMandat: 'Exclusif',
    conjoint: 'Nadia El Fassi',
    agentDesigne: 'agent-1',
    documents: [
      { name: 'CIN - Hassan El Fassi.pdf', url: '#', type: 'identity', uploadedAt: '2026-06-01', category: 'identite', size: '1.8 Mo' },
      { name: 'Justificatif de domicile - Hassan El Fassi.pdf', url: '#', type: 'proof_address', uploadedAt: '2026-05-15', category: 'identite', size: '1.2 Mo' },
      { name: 'Mandat de vente exclusif - Villa Argana.pdf', url: '#', type: 'mandate_sale', uploadedAt: '2026-06-01', category: 'mandat', size: '2.4 Mo' },
      { name: 'Titre de propriété - Villa Argana.pdf', url: '#', type: 'title_deed', uploadedAt: '2026-05-20', category: 'juridique', size: '3.5 Mo' },
    ],
    events: [
      {
        id: 'event-4-1',
        type: 'email',
        date: '2026-06-01T10:00:00Z',
        summary: 'Signature du mandat de vente',
        agent: 'John Doe'
      }
    ],
    createdAt: '2026-06-01',
    updatedAt: '2026-06-05',
    createdBy: 'system',
  },
  {
    id: '5',
    name: 'Fatima Zahra Bennani',
    type: 'Vendeur',
    status: 'Actif',
    phone: '+212 6 12 34 56 79',
    email: 'fatima.bennani@example.com',
    propertyType: 'Appartement',
    area: 'Maroc',
    secteur: 'Sidi Magdoul',
    minSurface: 85,
    surfaceMax: 85,
    rooms: '3',
    prixMin: 650000,
    prixMax: 650000,
    devise: 'MAD',
    classification: 'Normal',
    statutMetier: 'En attente de signature',
    croisementAutomatique: false,
    categorie: 'Vente',
    pieces: 3,
    chambres: 2,
    etat: 'Bon',
    standing: 'Moyen',
    disponibilite: 'Immediate',
    attributPrincipal: 'Residence secondaire',
    criteres: ['Balcon', 'Parking', 'Ascenseur'],
    proximites: {
      transports: ['Bus', 'Taxi', 'Tram'],
      commerces: ['Commerces', 'Supermarché'],
      education: ['Ecole primaire'],
      sante: ['Medecin'],
      loisirs: ['Mer', 'Plage'],
    },
    prestations: {
      exterieur: ['Videophone', 'Interphone'],
      confort: ['Double vitrage', 'Ascenseur'],
      electromenager: [],
      multimedia: ['Internet'],
      sport: [],
    },
    currentSituation: 'Proprietaire bailleur',
    reasonForSelling: 'Investissement - revente après plus-value',
    notes: 'Appartement bien situé, proche de la plage. Idéal pour investissement locatif.',
    lastContact: '2026-06-03',
    createdAt: '2026-05-20',
    updatedAt: '2026-06-03',
    createdBy: 'system',
  },
  {
    id: '6',
    name: 'Omar Tazi',
    type: 'Vendeur',
    status: 'Inactif',
    phone: '+212 6 45 67 89 01',
    email: 'omar.tazi@example.com',
    propertyType: 'Terrain',
    area: 'Maroc',
    secteur: 'Azlef',
    minSurface: 500,
    surfaceMax: 1000,
    rooms: '',
    prixMin: 1200000,
    prixMax: 1800000,
    devise: 'MAD',
    classification: 'Peu actif',
    statutMetier: 'Perdu',
    croisementAutomatique: false,
    categorie: 'Vente',
    currentSituation: 'SCI',
    reasonForSelling: 'Vente ailleurs - a trouvé un acquéreur via une autre agence',
    notes: 'Terrain constructible viabilisé. Client peu réactif, probablement déjà vendu ailleurs.',
    lastContact: '2026-05-10',
    events: [],
    createdAt: '2026-04-01',
    updatedAt: '2026-05-10',
    createdBy: 'system',
  },
  {
    id: '3',
    name: 'Karim Benali',
    type: 'Acheteur',
    status: 'En négociation',
    phone: '+212 6 12 34 56 78',
    email: 'karim.benali@example.com',
    propertyType: 'Appartement',
    area: 'Maroc',
    secteur: 'Sidi Magdoul',
    minSurface: 60,
    surfaceMax: 90,
    rooms: '2',
    prixMin: 400000,
    prixMax: 600000,
    devise: 'MAD',
    classification: 'Normal',
    statutMetier: 'En qualification',
    categorie: 'Programme',
    pieces: 2,
    chambres: 1,
    etat: 'Neuf',
    standing: 'Economique',
    disponibilite: 'Immediate',
    attributPrincipal: 'Premiere occupation',
    criteres: ['Parking', 'Ascenseur', 'Balcon'],
    contribution: 80000,
    financingType: 'Pret bancaire',
    loanDuration: 20,
    capaciteEmprunt: 200000,
    currentSituation: 'Heberge',
    urgency: 'Immediate',
    moveInDate: '2025-07-01',
    notes: 'Primo-accédant, budget serré. Programme neuf avec livraison rapide.',
    lastContact: '2025-06-12',
    events: [],
    createdAt: '2025-06-01',
    updatedAt: '2025-06-12',
    createdBy: 'system',
  },
  {
    id: '7',
    name: 'Ahmed Benali',
    type: 'Bailleur',
    status: 'Actif',
    phone: '+212 6 11 22 33 44',
    email: 'ahmed.benali@example.com',
    propertyType: 'Appartement',
    area: 'Maroc',
    secteur: 'Erraounak',
    minSurface: 70,
    surfaceMax: 70,
    rooms: '2',
    prixMin: undefined,
    prixMax: undefined,
    devise: 'MAD',
    classification: 'Actif',
    statutMetier: 'En mandat',
    croisementAutomatique: true,
    categorie: 'Location',
    pieces: 2,
    chambres: 1,
    etat: 'Bon',
    standing: 'Moyen',
    disponibilite: 'Immediate',
    attributPrincipal: 'Investissement locatif',
    criteres: ['Parking', 'Ascenseur', 'Balcon'],
    proximites: {
      transports: ['Bus', 'Tram', 'Taxi'],
      commerces: ['Commerces', 'Supermarché'],
      education: ['Ecole primaire'],
      sante: ['Medecin'],
      loisirs: ['Mer', 'Plage'],
    },
    prestations: {
      exterieur: ['Videophone', 'Interphone', 'Digicode'],
      confort: ['Double vitrage', 'Ascenseur', 'Air conditionne'],
      electromenager: ['Lave-linge', 'Refrigerateur', 'Four'],
      multimedia: ['Internet'],
      sport: [],
    },
    currentSituation: 'Proprietaire bailleur',
    reasonForSelling: 'Investissement locatif',
    notes: 'Bailleur régulier avec plusieurs biens en gestion. Appartement meublé disponible immédiatement.',
    lastContact: '2026-06-05',
    numeroMandat: 'MG-2026-001',
    dateSignature: '2026-06-01',
    dateDebut: '2026-06-01',
    dateExpiration: '2027-06-01',
    statutMandat: 'Actif',
    typeMandat: 'Gestion',
    conjoint: '',
    agentDesigne: 'agent-1',
    typeRemuneration: 'Frais de gestion mensuels',
    montantRemuneration: 500,
    conditionPaiement: 'Preleve sur loyer',
    events: [
      {
        id: 'event-7-1',
        type: 'email',
        date: '2026-06-01T10:00:00Z',
        summary: 'Signature du mandat de gestion',
        agent: 'John Doe'
      }
    ],
    createdAt: '2026-06-01',
    updatedAt: '2026-06-05',
    createdBy: 'system',
  },
  {
    id: '8',
    name: 'Nadia El Fassi',
    type: 'Bailleur',
    status: 'Actif',
    phone: '+212 6 55 66 77 88',
    email: 'nadia.elfassi@example.com',
    propertyType: 'Villa',
    area: 'Maroc',
    secteur: 'Ghazoua',
    minSurface: 150,
    surfaceMax: 200,
    rooms: '4',
    prixMin: undefined,
    prixMax: undefined,
    devise: 'MAD',
    classification: 'Normal',
    statutMetier: 'En attente de signature',
    croisementAutomatique: false,
    categorie: 'Location',
    pieces: 4,
    chambres: 3,
    etat: 'Neuf',
    standing: 'Luxe',
    disponibilite: '3 mois',
    attributPrincipal: 'Residence secondaire',
    attributsPersonnalises: ['Piscine chauffee', 'Cheminee'],
    criteres: ['Jardin', 'Garage', 'Piscine', 'Terrasse'],
    proximites: {
      transports: ['Aeroport', 'Autoroute'],
      commerces: ['Centre ville'],
      education: [],
      sante: [],
      loisirs: ['Golf', 'Mer'],
    },
    prestations: {
      exterieur: ['Portail electrique', 'Video surveillance', 'Piscine'],
      confort: ['Cheminee', 'Domotique', 'Piscine', 'Air conditionne'],
      electromenager: ['Cuisiniere', 'Lave-vaisselle', 'Refrigerateur'],
      multimedia: ['Internet', 'Teledistribution'],
      sport: [],
    },
    currentSituation: 'Proprietaire occupant',
    reasonForSelling: 'Demenagement',
    notes: 'Villa luxueuse à louer pour cause de déménagement à l\'étranger. Recherche locataire sérieux.',
    lastContact: '2026-06-03',
    documents: [
      { name: 'CIN - Nadia El Fassi.pdf', url: '#', type: 'identity', uploadedAt: '2026-05-20', category: 'identite', size: '1.9 Mo' },
      { name: 'Mandat de gestion - Nadia El Fassi.pdf', url: '#', type: 'mandate_management', uploadedAt: '2026-06-01', category: 'mandat', size: '2.1 Mo' },
    ],
    createdAt: '2026-05-15',
    updatedAt: '2026-06-03',
    createdBy: 'system',
  },
  {
    id: '9',
    name: 'Sophie Laurent',
    type: 'Locataire',
    status: 'Actif',
    phone: '+33 6 23 45 67 89',
    email: 'sophie.laurent@example.com',
    propertyType: 'Appartement',
    area: 'Maroc',
    secteur: 'Medina',
    minSurface: 50,
    surfaceMax: 80,
    rooms: '2',
    prixMin: 4000,
    devise: 'MAD',
    classification: 'Tres actif',
    statutMetier: 'En recherche',
    croisementAutomatique: true,
    categorie: 'Location',
    pieces: 2,
    chambres: 1,
    etat: 'Bon',
    standing: 'Moyen',
    disponibilite: 'Immediate',
    attributPrincipal: 'Premiere occupation',
    criteres: ['Balcon', 'Parking', 'Meuble', 'Animaux acceptes'],
    proximites: {
      transports: ['Bus', 'Tram'],
      commerces: ['Commerces', 'Supermarché'],
      education: ['Universite'],
      sante: ['Medecin'],
      loisirs: ['Parc', 'Cinema'],
    },
    prestations: {
      exterieur: ['Videophone', 'Digicode'],
      confort: ['Double vitrage', 'Air conditionne', 'Fibre optique', 'Meuble'],
      electromenager: ['Lave-linge', 'Refrigerateur', 'Four micro-ondes'],
      multimedia: ['Internet'],
      sport: [],
    },
    employmentStatus: 'Etudiant',
    contribution: 12000,
    guarantor: true,
    currentSituation: 'Heberge',
    moveInDate: '2026-07-01',
    notes: 'Étudiante en master, cherche un studio ou 2 pièces meublé. Budget serré, garante disponible.',
    lastContact: '2026-06-08',
    numeroMandat: 'MLR-2026-001',
    dateSignature: '2026-06-01',
    dateDebut: '2026-06-01',
    dateExpiration: '2026-12-01',
    statutMandat: 'Actif',
    typeMandat: 'Non-exclusif',
    agentDesigne: 'agent-2',
    typeRemuneration: 'Honoraires de location',
    montantRemuneration: 3000,
    conditionPaiement: 'Signature bail',
    dureeProtection: '3',
    documents: [
      { name: 'CIN - Sophie Laurent.pdf', url: '#', type: 'identity', uploadedAt: '2026-06-01', category: 'identite', size: '1.5 Mo' },
      { name: 'Justificatif de domicile - Sophie Laurent.pdf', url: '#', type: 'proof_address', uploadedAt: '2026-06-01', category: 'identite', size: '1.1 Mo' },
      { name: 'Fiches de paie - Sophie Laurent (3 mois).pdf', url: '#', type: 'payslip', uploadedAt: '2026-06-03', category: 'financier', size: '2.8 Mo' },
      { name: "Relevé d'identité bancaire - Sophie Laurent.pdf", url: '#', type: 'bank_statement', uploadedAt: '2026-06-03', category: 'financier', size: '0.5 Mo' },
      { name: 'Mandat de recherche - Sophie Laurent.pdf', url: '#', type: 'mandate_search', uploadedAt: '2026-06-01', category: 'mandat', size: '0.8 Mo' },
    ],
    events: [
      {
        id: 'event-9-1',
        type: 'email',
        date: '2026-06-01T10:00:00Z',
        summary: 'Inscription et signature du mandat de recherche',
        agent: 'John Doe'
      }
    ],
    createdAt: '2026-06-01',
    updatedAt: '2026-06-08',
    createdBy: 'system',
  },
  {
    id: '10',
    name: 'Marc Dubois',
    type: 'Locataire',
    status: 'Actif',
    phone: '+33 6 34 56 78 90',
    email: 'marc.dubois@example.com',
    propertyType: 'Maison',
    area: 'Maroc',
    secteur: 'Ghazoua',
    minSurface: 100,
    surfaceMax: 150,
    rooms: '4',
    prixMin: 8000,
    devise: 'MAD',
    classification: 'Actif',
    statutMetier: 'En visite',
    croisementAutomatique: true,
    categorie: 'Location',
    pieces: 4,
    chambres: 3,
    etat: 'Tres bon',
    standing: 'Luxe',
    disponibilite: '1 mois',
    attributPrincipal: 'Residence secondaire',
    criteres: ['Jardin', 'Garage', 'Piscine', 'Terrasse'],
    proximites: {
      transports: ['Autoroute', 'Gare'],
      commerces: ['Centre ville', 'Supermarché'],
      education: ['Ecole primaire', 'Ecole secondaire'],
      sante: ['Hopital / Clinique'],
      loisirs: ['Golf', 'Parc'],
    },
    prestations: {
      exterieur: ['Portail electrique', 'Video surveillance', 'Piscine', 'Jardin'],
      confort: ['Cheminee', 'Domotique', 'Piscine', 'Spa', 'Fibre optique'],
      electromenager: ['Cuisiniere', 'Lave-vaisselle', 'Refrigerateur'],
      multimedia: ['Internet', 'Teledistribution'],
      sport: [],
    },
    employmentStatus: 'CDI',
    contribution: 35000,
    guarantor: false,
    currentSituation: 'Locataire',
    moveInDate: '2026-07-15',
    notes: 'Famille avec 2 enfants, cherche maison avec jardin et piscine. CDI cadre supérieur, budget confortable.',
    lastContact: '2026-06-09',
    numeroMandat: 'MLR-2026-002',
    dateSignature: '2026-06-05',
    dateDebut: '2026-06-05',
    dateExpiration: '2026-12-05',
    statutMandat: 'Actif',
    typeMandat: 'Exclusif',
    conjoint: 'Camille Dubois',
    agentDesigne: 'agent-1',
    typeRemuneration: 'Honoraires de location',
    montantRemuneration: 5000,
    conditionPaiement: 'Signature bail',
    dureeProtection: '3',
    events: [
      {
        id: 'event-10-1',
        type: 'email',
        date: '2026-06-05T10:00:00Z',
        summary: 'Signature du mandat de recherche exclusif',
        agent: 'John Doe'
      },
      {
        id: 'event-10-2',
        type: 'visite',
        date: '2026-06-08T14:00:00Z',
        summary: 'Visite villa Ghazoua - très intéressé',
        agent: 'John Doe'
      }
    ],
    createdAt: '2026-06-05',
    updatedAt: '2026-06-09',
    createdBy: 'system',
  },
  {
    id: '11',
    name: 'Thomas & Emma Berger',
    type: 'Voyageur',
    status: 'Actif',
    phone: '+33 6 45 67 89 01',
    email: 'thomas.emma@example.com',
    propertyType: 'Riad',
    area: 'Maroc',
    secteur: 'Essaouira',
    minSurface: 80,
    surfaceMax: 120,
    rooms: '4',
    pieces: 2,
    chambres: 2,
    prixMin: 300,
    prixMax: 500,
    devise: 'EUR',
    nbPersonnes: 4,
    classification: 'Actif',
    statutMetier: 'Confirme',
    croisementAutomatique: true,
    categorie: 'Location saisonnière',
    etat: 'Tres bon',
    standing: 'Luxe',
    attributPrincipal: 'Vacances en famille',
    criteres: ['Piscine privee', 'Jardin', 'Air conditionne'],
    proximites: {
      transports: ['Aeroport', 'Taxi'],
      commerces: ['Restaurants', 'Supermarché', 'Centre ville'],
      education: [],
      sante: ['Pharmacie'],
      loisirs: ['Mer', 'Plage', 'Golf'],
    },
    prestations: {
      exterieur: ['Piscine privee', 'Jardin', 'Terrasse', 'Barbecue', 'Parking prive'],
      confort: ['Wifi haut debit', 'Climatisation', 'Lave-linge', 'Cintres'],
      electromenager: ['Refrigerateur', 'Micro-ondes', 'Cafetiere', 'Ustensiles cuisine'],
      multimedia: ['Smart TV', 'Netflix', 'Enceinte Bluetooth'],
      sport: [],
    },
    budgetParNuitMin: 300,
    budgetParNuitMax: 500,
    dateArrivee: '2026-07-15',
    dateDepart: '2026-07-22',
    flexibiliteDates: 'Pas flexible',
    modePaiement: 'Carte bancaire',
    acompteVersee: 840,
    caution: 1000,
    conditionsAnnulation: 'Moderee',
    notes: 'Famille avec 2 enfants (8 et 5 ans). Souhaitent riad avec piscine proche de la plage. Viennent de Genève.',
    lastContact: '2026-06-10',
    numeroMandat: 'RES-2026-001',
    dateSignature: '2026-06-01',
    dateDebut: '2026-07-15',
    dateExpiration: '2026-07-22',
    statutMandat: 'Actif',
    typeMandat: 'Moderee',
    conjoint: 'Français, Anglais',
    dureeProtection: 'Pas flexible',
    documents: [
      { name: 'Passeport - Thomas Berger.pdf', url: '#', type: 'identity', uploadedAt: '2026-06-01', category: 'identite', size: '2.2 Mo' },
      { name: 'Passeport - Emma Berger.pdf', url: '#', type: 'identity', uploadedAt: '2026-06-01', category: 'identite', size: '2.1 Mo' },
      { name: 'Contrat de location saisonnière signé.pdf', url: '#', type: 'seasonal_contract', uploadedAt: '2026-06-05', category: 'extranet', size: '1.6 Mo' },
      { name: 'Règlement intérieur accepté.pdf', url: '#', type: 'policy', uploadedAt: '2026-06-05', category: 'extranet', size: '0.7 Mo' },
      { name: 'Consentement RGPD signé.pdf', url: '#', type: 'policy', uploadedAt: '2026-06-01', category: 'extranet', size: '0.3 Mo' },
    ],
    events: [
      {
        id: 'event-11-1',
        type: 'email',
        date: '2026-06-01T09:00:00Z',
        summary: 'Demande de réservation - Riad 2 chambres',
        agent: 'John Doe'
      },
      {
        id: 'event-11-2',
        type: 'email',
        date: '2026-06-05T14:00:00Z',
        summary: 'Confirmation de la réservation et paiement acompte',
        agent: 'John Doe'
      }
    ],
    createdAt: '2026-06-01',
    updatedAt: '2026-06-10',
    createdBy: 'system',
  },
  {
    id: '12',
    name: 'Sarah Klein',
    type: 'Voyageur',
    status: 'Actif',
    phone: '+33 6 56 78 90 12',
    email: 'sarah.klein@example.com',
    propertyType: 'Studio',
    area: 'Maroc',
    secteur: 'Medina',
    minSurface: 30,
    surfaceMax: 50,
    rooms: '1',
    pieces: 1,
    chambres: 1,
    prixMin: 150,
    prixMax: 250,
    devise: 'EUR',
    nbPersonnes: 2,
    classification: 'Actif',
    statutMetier: 'En recherche',
    croisementAutomatique: true,
    categorie: 'Location saisonnière',
    attributPrincipal: 'Teletravail Workation',
    criteres: ['Air conditionne', 'Chauffage'],
    proximites: {
      transports: ['Aeroport', 'Gare', 'Bus'],
      commerces: ['Restaurants', 'Commerces'],
      education: [],
      sante: ['Pharmacie', 'Medecin'],
      loisirs: ['Mer', 'Plage', 'Parc'],
    },
    prestations: {
      exterieur: ['Terrasse', 'Local velos'],
      confort: ['Wifi haut debit', 'Climatisation', 'Chauffage', 'Fer a repasser', 'Cintres'],
      electromenager: ['Refrigerateur', 'Micro-ondes', 'Plaque cuisson', 'Cafetiere', 'Bouilloire'],
      multimedia: ['Smart TV', 'Netflix'],
      sport: [],
    },
    notes: 'Journaliste freelance, cherche studio meublé avec bon wifi pour télétravailler 3 semaines. Préfère le quartier de la Médina.',
    lastContact: '2026-06-09',
    numeroMandat: 'RES-2026-002',
    dateSignature: '2026-06-08',
    dateDebut: '',
    dateExpiration: '',
    statutMandat: 'En attente',
    typeMandat: 'Flexible',
    conjoint: 'Français, Anglais, Allemand',
    dureeProtection: 'Flexible 3 jours',
    events: [
      {
        id: 'event-12-1',
        type: 'email',
        date: '2026-06-08T11:00:00Z',
        summary: "Inscription - Recherche studio pour télétravail",
        agent: 'John Doe'
      }
    ],
    createdAt: '2026-06-08',
    updatedAt: '2026-06-09',
    createdBy: 'system',
  },
];

export { sampleClients };