export type AutomatorCategorie = 'calendrier' | 'contrats' | 'extranet' | 'contacts'
export type AutomatorNiveau = 'entreprise' | 'agence' | 'utilisateur'
export type NotificationCanal = 'email' | 'sms' | 'push' | 'application_mobile'
export type LogStatut = 'succes' | 'echec' | 'en_attente'

export interface AutomatorModele {
  id: number
  nom: string
  description: string
  categorie: AutomatorCategorie
  evenementType: string
  variablesDisponibles: string[]
  icone: string
}

export interface AutomatorNotification {
  id: number
  automatorId: number
  canal: NotificationCanal
  actif: boolean
  langue: string
  objetTemplate?: string
  messageTemplate: string
  destinataires: string[]
}

export interface AutomatorLog {
  id: number
  automatorId: number
  evenement: string
  destinataire: string
  statut: LogStatut
  messageErreur?: string
  executeLe: string
  contenu?: string
}

export interface Automator {
  id: number
  modeleId: number
  eventId?: string
  niveau: AutomatorNiveau
  niveauLabel: string
  nomPersonnalise?: string
  createdBy: string
  delegatedBy?: string
  delegatedTo?: string
  delegationType?: 'all' | 'specific'
  actif: boolean
  frequence: string
  derniereExecution?: string
  notifications: AutomatorNotification[]
  createdAt: string
}

export const CATEGORIE_LABELS: Record<AutomatorCategorie, string> = {
  calendrier: 'Calendrier',
  contrats: 'Contrats',
  extranet: 'Squarepeek',
  contacts: 'Contacts',
}

export const CATEGORIE_ICONES: Record<AutomatorCategorie, string> = {
  calendrier: 'calendar',
  contrats: 'file-text',
  extranet: 'globe',
  contacts: 'users',
}

export const mockModeles: AutomatorModele[] = [
  { id: 1, nom: 'Rappel de rendez-vous utilisateur 1 heure avant', description: 'Envoi automatique d\'un message de rappel de rendez-vous à l\'agent 1 heure avant', categorie: 'calendrier', evenementType: 'rendez_vous_agent', variablesDisponibles: ['_target.contact.firstname', '_target.start_at', '_target.subject', '_target.property.address'], icone: 'calendar' },
  { id: 2, nom: 'Rappel de rendez-vous contact 1 heure avant', description: 'Envoi automatique d\'un message de rappel de rendez-vous au client 1 heure avant', categorie: 'calendrier', evenementType: 'rendez_vous_contact', variablesDisponibles: ['_target.contact.firstname', '_target.start_at', '_target.subject', '_target.property.address'], icone: 'calendar' },
  { id: 5, nom: 'Remerciement vente d\'un bien', description: 'Message au vendeur suite à la vente d\'un bien', categorie: 'contrats', evenementType: 'vente_finalisee', variablesDisponibles: ['_target.vendeur.nom', '_target.produit.titre', '_target.prix_vente'], icone: 'file-text' },
  { id: 6, nom: 'Remerciement pour l\'achat/location', description: 'Message à l\'acheteur/locataire suite à la transaction', categorie: 'contrats', evenementType: 'achat_finalise', variablesDisponibles: ['_target.acheteur.nom', '_target.produit.titre', '_target.prix'], icone: 'file-text' },
  { id: 7, nom: 'Remerciement prise de mandat', description: 'Message au propriétaire suite à la signature d\'un mandat', categorie: 'contrats', evenementType: 'mandat_signe', variablesDisponibles: ['_target.proprietaire.nom', '_target.produit.titre', '_target.type_mandat'], icone: 'file-text' },
  { id: 8, nom: 'Alerte fin période de réflexion', description: 'Avertissement 24h avant la fin du délai légal', categorie: 'contrats', evenementType: 'fin_periode_reflexion', variablesDisponibles: ['_target.contact.nom', '_target.produit.titre', '_target.date_limite'], icone: 'file-text' },
  { id: 9, nom: 'Identifiants Squaremeter', description: 'Envoi automatique des identifiants aux nouveaux contacts', categorie: 'extranet', evenementType: 'extranet_nouveau_compte', variablesDisponibles: ['_target.contact.nom', '_target.email', '_target.mot_de_passe_temporaire', '_target.lien_connexion'], icone: 'globe' },
  { id: 10, nom: 'Nouvelle action Squaremeter', description: 'Notification lors d\'un nouveau document sur l\'espace client', categorie: 'extranet', evenementType: 'extranet_nouvelle_action', variablesDisponibles: ['_target.contact.nom', '_target.action_type'], icone: 'globe' },
  { id: 11, nom: 'Souhaiter l\'anniversaire', description: 'Message automatique le jour de l\'anniversaire du contact', categorie: 'contacts', evenementType: 'anniversaire', variablesDisponibles: ['_target.contact.prenom', '_target.contact.age'], icone: 'users' },
]

export const mockAutomators: Automator[] = []

export const mockLogs: AutomatorLog[] = []

export const LOG_STATUT_LABELS: Record<LogStatut, string> = {
  succes: 'Succès',
  echec: 'Échec',
  en_attente: 'En attente',
}

export const getModeleById = (id: number) => mockModeles.find(m => m.id === id)
export const getAutomatorLogs = (automatorId: number) => mockLogs.filter(l => l.automatorId === automatorId)
export const getModelesByCategorie = (cat: AutomatorCategorie) => mockModeles.filter(m => m.categorie === cat)
export const getEventById = (id: string) => EVENTS.find(e => e.id === id)

export type RecipientType = 'agent' | 'client' | 'both'

export type ClientType = 'acheteur' | 'vendeur' | 'bailleur' | 'locataire' | 'voyageur' | 'contacts' | 'calendrier' | 'contrats' | 'extranet' | 'admin' | 'tous'

export interface NotificationTemplate {
  emailObjet: string
  emailMessage: string
  smsMessage: string
}

export interface AutomatorEvent {
  id: string
  label: string
  description: string
  defaultRecipient: RecipientType
  clientType: ClientType
  agentTemplate: NotificationTemplate
  clientTemplate?: NotificationTemplate
}

export const REAL_CLIENT_TYPES = new Set(['acheteur', 'vendeur', 'bailleur', 'locataire', 'voyageur'])

export const CLIENT_TYPE_CONFIG: { key: ClientType; label: string; color: string }[] = [
  { key: 'tous', label: 'Tous', color: 'text-text-secondary' },
  { key: 'acheteur', label: 'Acheteur', color: 'text-blue-600' },
  { key: 'vendeur', label: 'Vendeur', color: 'text-emerald-600' },
  { key: 'bailleur', label: 'Bailleur', color: 'text-purple-600' },
  { key: 'locataire', label: 'Locataire', color: 'text-amber-600' },
  { key: 'voyageur', label: 'Voyageur', color: 'text-rose-600' },
  { key: 'contacts', label: 'Contacts', color: 'text-cyan-600' },
  { key: 'calendrier', label: 'Calendrier', color: 'text-orange-600' },
  { key: 'contrats', label: 'Contrats', color: 'text-indigo-600' },
  { key: 'extranet', label: 'Squarepeek', color: 'text-teal-600' },
  { key: 'admin', label: 'Admin (Système)', color: 'text-slate-600' },
]


export const EVENTS: AutomatorEvent[] = [
  { id: "acheteur_demande_recherche_creer", label: "Nouvelle demande de recherche créée", description: "L'acheteur crée une nouvelle demande de recherche", defaultRecipient: "both", clientType: "acheteur",
    agentTemplate: { emailObjet: "Nouvelle demande de recherche - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a créé une nouvelle demande de recherche.\\n\\nCritères : {{demande.criteres}}\\n\\nBudget : {{demande.budget_min}} - {{demande.budget_max}} €\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Nouvelle demande de {{client.prenom}} {{client.nom}} : {{demande.criteres}}" },
    clientTemplate: { emailObjet: "Confirmation de votre demande de recherche", emailMessage: "Bonjour {{client.prenom}},\\n\\nNous avons bien reçu votre demande de recherche.\\n\\nCritères : {{demande.criteres}}\\n\\nBudget : {{demande.budget_min}} - {{demande.budget_max}} €\\n\\nNotre équipe va rechercher les biens correspondant à vos critères.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Votre demande de recherche a bien été prise en compte. Nous vous contacterons rapidement." } },
  { id: "acheteur_demande_recherche_modifiee", label: "Demande de recherche modifiée", description: "L'acheteur modifie ses critères de recherche", defaultRecipient: "both", clientType: "acheteur",
    agentTemplate: { emailObjet: "Demande de recherche modifiée - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a modifié sa demande de recherche.\\n\\nNouveaux critères : {{demande.criteres}}\\n\\nBudget : {{demande.budget_min}} - {{demande.budget_max}} €\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Demande modifiée - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Votre demande de recherche a été modifiée", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre demande de recherche a bien été mise à jour.\\n\\nCritères : {{demande.criteres}}\\n\\nBudget : {{demande.budget_min}} - {{demande.budget_max}} €\\n\\nNous continuons à rechercher les meilleurs biens pour vous.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Votre demande de recherche a été mise à jour." } },
  { id: "acheteur_croisement", label: "Nouveau croisement trouvé", description: "Un bien correspond aux critères de l'acheteur", defaultRecipient: "both", clientType: "acheteur",
    agentTemplate: { emailObjet: "Nouveau croisement trouvé pour {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nNouveau croisement trouvé pour le client {{client.prenom}} {{client.nom}}.\\n\\nBien : {{bien.titre}} - {{bien.prix}} €\\n\\nSurface : {{bien.surface}} m² · {{bien.pieces}} pièces\\n\\nCorrespondance : {{score}}%\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Croisement : {{bien.titre}} pour {{client.prenom}} {{client.nom}} - {{score}}%" },
    clientTemplate: { emailObjet: "Nouveau bien correspondant à vos critères", emailMessage: "Bonjour {{client.prenom}},\\n\\nNous avons trouvé un nouveau bien qui correspond à vos critères :\\n\\n{{bien.titre}} - {{bien.prix}} €\\n\\nSurface : {{bien.surface}} m² · {{bien.pieces}} pièces · {{bien.chambres}} chambres\\n\\nCorrespondance : {{score}}%\\n\\nVoir le bien : {{lien_client}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Nouveau bien trouvé : {{bien.titre}} - {{bien.prix}} €. {{lien_client}}" } },
  { id: "acheteur_proposition_consultee", label: "Proposition de bien consultée", description: "L'acheteur consulte une proposition de bien", defaultRecipient: "agent", clientType: "acheteur",
    agentTemplate: { emailObjet: "Proposition consultée par {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a consulté la proposition suivante :\\n\\nBien : {{bien.titre}} - {{bien.prix}} €\\n\\nDate de consultation : {{consultation.date}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "{{client.prenom}} {{client.nom}} a consulté {{bien.titre}}" } },
  { id: "acheteur_proposition_sauvegardee", label: "Proposition de bien sauvegardée", description: "L'acheteur sauvegarde un bien en favori", defaultRecipient: "agent", clientType: "acheteur",
    agentTemplate: { emailObjet: "Bien sauvegardé par {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a sauvegardé le bien suivant :\\n\\nBien : {{bien.titre}} - {{bien.prix}} €\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Favori : {{bien.titre}} ajouté par {{client.prenom}} {{client.nom}}" } },
  { id: "acheteur_demande_visite", label: "Demande de visite effectuée", description: "L'acheteur demande une visite", defaultRecipient: "both", clientType: "acheteur",
    agentTemplate: { emailObjet: "Nouvelle demande de visite - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a demandé une visite pour le bien :\\n\\n{{bien.titre}} - {{bien.prix}} €\\n\\nDate souhaitée : {{visite.date}} à {{visite.heure}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Demande de visite : {{client.prenom}} {{client.nom}} - {{bien.titre}} le {{visite.date}}" },
    clientTemplate: { emailObjet: "Confirmation de votre demande de visite", emailMessage: "Bonjour {{client.prenom}},\\n\\nNous avons bien reçu votre demande de visite pour le bien :\\n\\n{{bien.titre}} - {{bien.prix}} €\\n\\nDate souhaitée : {{visite.date}} à {{visite.heure}}\\n\\nNous vous confirmerons le rendez-vous très prochainement.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Votre demande de visite pour {{bien.titre}} le {{visite.date}} a été reçue." } },
  { id: "acheteur_rappel_visite_24h", label: "Rappel de visite (24h avant)", description: "24h avant la date de visite", defaultRecipient: "client", clientType: "acheteur",
    agentTemplate: { emailObjet: "Rappel visite 24h - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nRappel : {{client.prenom}} {{client.nom}} a une visite demain.\\n\\nBien : {{bien.titre}}\\n\\nDate : {{visite.date}} à {{visite.heure}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Rappel : visite demain pour {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Rappel - Votre visite demain", emailMessage: "Bonjour {{client.prenom}},\\n\\nRappel de votre visite prévue demain :\\n\\nBien : {{bien.titre}}\\n\\nDate : {{visite.date}} à {{visite.heure}}\\n\\nAdresse : {{bien.adresse}}\\n\\nÀ demain !\\n\\nL'équipe Square Meter", smsMessage: "Rappel : visite demain à {{visite.heure}} - {{bien.adresse}}" } },
  { id: "acheteur_rappel_visite_1h", label: "Rappel de visite (1h avant)", description: "1h avant la date de visite", defaultRecipient: "client", clientType: "acheteur",
    agentTemplate: { emailObjet: "Rappel visite 1h - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nRappel : {{client.prenom}} {{client.nom}} a une visite dans 1 heure.\\n\\nBien : {{bien.titre}}\\n\\nAdresse : {{bien.adresse}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Rappel : visite dans 1h - {{bien.adresse}}" },
    clientTemplate: { emailObjet: "Rappel - Votre visite dans 1 heure", emailMessage: "Bonjour {{client.prenom}},\\n\\nRappel : votre visite est dans 1 heure.\\n\\nBien : {{bien.titre}}\\n\\nAdresse : {{bien.adresse}}\\n\\nÀ très vite !\\n\\nL'équipe Square Meter", smsMessage: "Rappel : visite dans 1h - {{bien.adresse}}" } },
  { id: "acheteur_offre_faite", label: "Offre faite sur un bien", description: "L'agent fait une offre à l'acheteur", defaultRecipient: "both", clientType: "acheteur",
    agentTemplate: { emailObjet: "Offre déposée - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nUne offre a été déposée par {{client.prenom}} {{client.nom}} :\\n\\nBien : {{bien.titre}}\\n\\nMontant de l'offre : {{offre.montant}} €\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Offre déposée par {{client.prenom}} {{client.nom}} - {{offre.montant}}€" },
    clientTemplate: { emailObjet: "Confirmation de votre offre - {{bien.titre}}", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre offre de {{offre.montant}} € pour le bien {{bien.titre}} a bien été déposée.\\n\\nNous vous tiendrons informé de la suite donnée par le vendeur.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Votre offre de {{offre.montant}}€ pour {{bien.titre}} a été déposée." } },
  { id: "acheteur_offre_acceptee", label: "Offre acceptée", description: "L'acheteur accepte l'offre", defaultRecipient: "both", clientType: "acheteur",
    agentTemplate: { emailObjet: "Offre acceptée - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a accepté l'offre pour {{bien.titre}}.\\n\\nMontant : {{offre.montant}} €\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Offre acceptée - {{bien.titre}} - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Offre acceptée - Félicitations !", emailMessage: "Bonjour {{client.prenom}},\\n\\nFélicitations ! Votre offre de {{offre.montant}} € pour {{bien.titre}} a été acceptée.\\n\\nNous vous accompagnons pour les prochaines étapes.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Félicitations ! Votre offre pour {{bien.titre}} a été acceptée." } },
  { id: "acheteur_offre_refusee", label: "Offre refusée", description: "L'acheteur refuse l'offre", defaultRecipient: "agent", clientType: "acheteur",
    agentTemplate: { emailObjet: "Offre refusée - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a refusé l'offre pour {{bien.titre}}.\\n\\nMontant de l'offre : {{offre.montant}} €\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Offre refusée - {{bien.titre}}" } },
  { id: "acheteur_compromis_signe", label: "Compromis signé", description: "Le compromis de vente est signé", defaultRecipient: "both", clientType: "acheteur",
    agentTemplate: { emailObjet: "Compromis signé - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLe compromis a été signé pour l'acquisition de {{bien.titre}} par {{client.prenom}} {{client.nom}}.\\n\\nMontant : {{bien.prix}} €\\n\\nDate de signature : {{signature.date}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Compromis signé - {{bien.titre}} - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Félicitations - Compromis signé !", emailMessage: "Bonjour {{client.prenom}},\\n\\nFélicitations ! Le compromis pour l'acquisition de {{bien.titre}} est signé.\\n\\nProchaine étape : la signature de l'acte authentique chez le notaire.\\n\\nNous restons à votre disposition.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Félicitations ! Le compromis pour {{bien.titre}} est signé." } },
  { id: "acheteur_document_ajoute", label: "Document ajouté par l'acheteur", description: "L'acheteur uploade un document", defaultRecipient: "agent", clientType: "acheteur",
    agentTemplate: { emailObjet: "Document ajouté - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a ajouté un nouveau document.\\n\\nDocument : {{document.nom}}\\n\\nType : {{document.type}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Document ajouté par {{client.prenom}} {{client.nom}}" } },
  { id: "acheteur_inactivite_30j", label: "Inactivité de l'acheteur (30j)", description: "Aucune activité depuis 30 jours", defaultRecipient: "agent", clientType: "acheteur",
    agentTemplate: { emailObjet: "Inactivité - {{client.prenom}} {{client.nom}} (30 jours)", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} n'a montré aucune activité depuis 30 jours.\\n\\nDernière activité : {{derniere_activite.date}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Inactivité 30j - {{client.prenom}} {{client.nom}}" } },
  { id: "vendeur_mandat_signe", label: "Nouveau mandat de vente signé", description: "Le mandat de vente est signé", defaultRecipient: "both", clientType: "vendeur",
    agentTemplate: { emailObjet: "Nouveau mandat signé - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nUn nouveau mandat de vente a été signé :\\n\\nClient : {{client.prenom}} {{client.nom}}\\n\\nBien : {{bien.titre}}\\n\\nType de mandat : {{mandat.type}}\\n\\nDurée : {{mandat.duree}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Mandat signé - {{client.prenom}} {{client.nom}} - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Confirmation de votre mandat de vente", emailMessage: "Bonjour {{client.prenom}},\\n\\nNous vous remercions pour votre confiance. Votre mandat de vente pour {{bien.titre}} a bien été signé.\\n\\nNotre équipe mettra tout en œuvre pour trouver le meilleur acquéreur.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Votre mandat de vente pour {{bien.titre}} est signé. Merci !" } },
  { id: "vendeur_demande_visite_recue", label: "Demande de visite reçue", description: "Un acheteur demande à visiter le bien", defaultRecipient: "both", clientType: "vendeur",
    agentTemplate: { emailObjet: "Demande de visite reçue - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nUne demande de visite a été reçue pour le bien {{bien.titre}}.\\n\\nVisiteur : {{visiteur.prenom}} {{visiteur.nom}}\\n\\nDate souhaitée : {{visite.date}} à {{visite.heure}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Demande de visite - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Demande de visite pour votre bien", emailMessage: "Bonjour {{client.prenom}},\\n\\nUne visite a été demandée pour votre bien {{bien.titre}}.\\n\\nNotre équipe vous contactera pour confirmer le rendez-vous.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Demande de visite pour {{bien.titre}}." } },
  { id: "vendeur_rappel_visite_24h", label: "Rappel de visite (24h avant)", description: "24h avant la date de visite", defaultRecipient: "client", clientType: "vendeur",
    agentTemplate: { emailObjet: "Rappel visite 24h - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nRappel : votre client {{client.prenom}} {{client.nom}} a une visite demain.\\n\\nBien : {{bien.titre}}\\n\\nDate : {{visite.date}} à {{visite.heure}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Rappel : visite demain - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Rappel - Visite de votre bien demain", emailMessage: "Bonjour {{client.prenom}},\\n\\nRappel : une visite de votre bien {{bien.titre}} est prévue demain.\\n\\nDate : {{visite.date}} à {{visite.heure}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Rappel : visite demain à {{visite.heure}} pour {{bien.titre}}" } },
  { id: "vendeur_offre_recue", label: "Offre d'achat reçue", description: "Une offre est déposée sur le bien", defaultRecipient: "both", clientType: "vendeur",
    agentTemplate: { emailObjet: "Offre d'achat reçue - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nUne offre d'achat a été reçue pour le bien :\\n\\nBien : {{bien.titre}}\\n\\nMontant : {{offre.montant}} €\\n\\nAcheteur : {{offre.acheteur}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Offre d'achat {{offre.montant}}€ - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Offre d'achat reçue pour votre bien", emailMessage: "Bonjour {{client.prenom}},\\n\\nUne offre d'achat de {{offre.montant}} € a été reçue pour votre bien {{bien.titre}}.\\n\\nNotre équipe vous contactera pour vous présenter les détails.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Offre d'achat de {{offre.montant}}€ reçue pour {{bien.titre}}" } },
  { id: "vendeur_offre_acceptee", label: "Offre d'achat acceptée", description: "L'offre est acceptée par le vendeur", defaultRecipient: "both", clientType: "vendeur",
    agentTemplate: { emailObjet: "Offre acceptée - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nLe vendeur {{client.prenom}} {{client.nom}} a accepté l'offre pour {{bien.titre}}.\\n\\nMontant : {{offre.montant}} €\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Offre acceptée - {{bien.titre}} - {{offre.montant}}€" },
    clientTemplate: { emailObjet: "Offre acceptée - Félicitations !", emailMessage: "Bonjour {{client.prenom}},\\n\\nFélicitations ! Vous avez accepté l'offre de {{offre.montant}} € pour {{bien.titre}}.\\n\\nNous vous accompagnons pour les prochaines étapes.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Offre acceptée pour {{bien.titre}}. Félicitations !" } },
  { id: "vendeur_offre_refusee", label: "Offre d'achat refusée", description: "L'offre est refusée", defaultRecipient: "agent", clientType: "vendeur",
    agentTemplate: { emailObjet: "Offre refusée - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nLe vendeur {{client.prenom}} {{client.nom}} a refusé l'offre pour {{bien.titre}}.\\n\\nMontant : {{offre.montant}} €\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Offre refusée - {{bien.titre}}" } },
  { id: "vendeur_compromis_signe", label: "Compromis signé", description: "Le compromis de vente est signé", defaultRecipient: "both", clientType: "vendeur",
    agentTemplate: { emailObjet: "Compromis signé - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nLe compromis de vente pour {{bien.titre}} a été signé.\\n\\nVendeur : {{client.prenom}} {{client.nom}}\\n\\nAcheteur : {{acheteur.prenom}} {{acheteur.nom}}\\n\\nMontant : {{bien.prix}} €\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Compromis signé - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Compromis signé pour {{bien.titre}}", emailMessage: "Bonjour {{client.prenom}},\\n\\nLe compromis de vente pour {{bien.titre}} est signé.\\n\\nProchaine étape : la signature de l'acte authentique.\\n\\nNous restons à votre disposition.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Compromis signé pour {{bien.titre}}." } },
  { id: "vendeur_vente_finalisee", label: "Vente finalisée", description: "La vente est conclue", defaultRecipient: "both", clientType: "vendeur",
    agentTemplate: { emailObjet: "Vente finalisée - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nLa vente de {{bien.titre}} est finalisée.\\n\\nMontant de vente : {{bien.prix}} €\\n\\nDate de finalisation : {{finalisation.date}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Vente finalisée - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Vente finalisée - Merci pour votre confiance", emailMessage: "Bonjour {{client.prenom}},\\n\\nLa vente de votre bien {{bien.titre}} est officiellement finalisée au prix de {{bien.prix}} €.\\n\\nNous vous remercions pour votre confiance tout au long de ce processus.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Vente de {{bien.titre}} finalisée. Merci pour votre confiance !" } },
  { id: "vendeur_mandat_expire_bientot", label: "Mandat expire bientôt (J-30)", description: "30 jours avant la fin du mandat", defaultRecipient: "both", clientType: "vendeur",
    agentTemplate: { emailObjet: "Mandat expire bientôt - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nLe mandat de vente pour {{bien.titre}} expire dans 30 jours.\\n\\nDate d'expiration : {{mandat.date_expiration}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Mandat expire J-30 - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Votre mandat expire bientôt", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre mandat de vente pour {{bien.titre}} expire dans 30 jours.\\n\\nSouhaitez-vous le renouveler ? Contactez-nous pour en discuter.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Votre mandat pour {{bien.titre}} expire dans 30 jours." } },
  { id: "vendeur_mandat_expire", label: "Mandat expiré", description: "Le mandat est expiré (statut Expiré ou date d'expiration atteinte)", defaultRecipient: "agent", clientType: "tous",
    agentTemplate: { emailObjet: "Mandat expiré - {{bien.titre}}", emailMessage: "Le mandat pour {{bien.titre}} est expiré.\n\nClient : {{client.prenom}} {{client.nom}}\nType de mandat : {{mandat.type}}\nDate d'expiration : {{mandat.date_expiration}}\nStatut : Expiré\n\nMerci de prendre les dispositions nécessaires.", smsMessage: "Mandat expiré - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Votre mandat pour {{bien.titre}} a expiré", emailMessage: "Bonjour {{client.prenom}},\n\nVotre mandat pour {{bien.titre}} a expiré le {{mandat.date_expiration}}.\n\nMerci de contacter votre agent pour toute question.\n\nCordialement,\nL'équipe Square Meter", smsMessage: "Votre mandat pour {{bien.titre}} a expiré." } },
  { id: "vendeur_document_demande", label: "Document demandé au vendeur", description: "L'agent demande un document (diagnostic, titre)", defaultRecipient: "client", clientType: "vendeur",
    agentTemplate: { emailObjet: "Document demandé à {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nVous avez demandé un document à {{client.prenom}} {{client.nom}}.\\n\\nDocument : {{document.nom}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Document demandé à {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Document demandé - {{bien.titre}}", emailMessage: "Bonjour {{client.prenom}},\\n\\nNous avons besoin du document suivant pour le dossier de {{bien.titre}} :\\n\\nDocument : {{document.nom}}\\n\\nMerci de nous le transmettre dès que possible.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Document requis : {{document.nom}} pour {{bien.titre}}" } },
  { id: "vendeur_document_recu", label: "Document reçu du vendeur", description: "Le vendeur uploade un document", defaultRecipient: "agent", clientType: "vendeur",
    agentTemplate: { emailObjet: "Document reçu - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a envoyé un document.\\n\\nDocument : {{document.nom}}\\n\\nType : {{document.type}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Document reçu de {{client.prenom}} {{client.nom}}" } },
  { id: "bailleur_mandat_gestion_signe", label: "Nouveau mandat de gestion signé", description: "Le mandat de gestion est signé", defaultRecipient: "both", clientType: "bailleur",
    agentTemplate: { emailObjet: "Mandat de gestion signé - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nUn mandat de gestion a été signé avec {{client.prenom}} {{client.nom}}.\\n\\nBien : {{bien.titre}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Mandat de gestion signé - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Confirmation de votre mandat de gestion", emailMessage: "Bonjour {{client.prenom}},\\n\\nNous vous remercions pour votre confiance. Votre mandat de gestion pour {{bien.titre}} est signé.\\n\\nNous assurons la gestion locative de votre bien avec la plus grande attention.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Mandat de gestion signé pour {{bien.titre}}. Merci !" } },
  { id: "bailleur_demande_location_recue", label: "Demande de location reçue", description: "Un locataire potentiel demande le bien", defaultRecipient: "both", clientType: "bailleur",
    agentTemplate: { emailObjet: "Demande de location reçue - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nUne demande de location a été reçue pour {{bien.titre}}.\\n\\nLocataire potentiel : {{locataire.prenom}} {{locataire.nom}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Demande location - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Demande de location pour votre bien", emailMessage: "Bonjour {{client.prenom}},\\n\\nUne demande de location a été reçue pour votre bien {{bien.titre}}.\\n\\nNotre équipe gère la sélection du locataire.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Demande de location pour {{bien.titre}}" } },
  { id: "bailleur_demande_visite_recue", label: "Demande de visite reçue", description: "Un locataire potentiel demande une visite", defaultRecipient: "both", clientType: "bailleur",
    agentTemplate: { emailObjet: "Demande de visite - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nUne demande de visite a été reçue pour {{bien.titre}}.\\n\\nVisiteur : {{visiteur.prenom}} {{visiteur.nom}}\\n\\nDate : {{visite.date}} à {{visite.heure}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Visite demandée - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Demande de visite pour votre bien", emailMessage: "Bonjour {{client.prenom}},\\n\\nUne visite a été demandée pour votre bien {{bien.titre}}.\\n\\nNous vous tiendrons informé.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Visite pour {{bien.titre}}" } },
  { id: "bailleur_rappel_visite_24h", label: "Rappel de visite (24h avant)", description: "24h avant la date de visite", defaultRecipient: "client", clientType: "bailleur",
    agentTemplate: { emailObjet: "Rappel visite 24h - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nRappel : une visite pour {{bien.titre}} a lieu demain.\\n\\nDate : {{visite.date}} à {{visite.heure}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Rappel visite demain - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Rappel - Visite de votre bien demain", emailMessage: "Bonjour {{client.prenom}},\\n\\nRappel : une visite de votre bien {{bien.titre}} est prévue demain.\\n\\nDate : {{visite.date}} à {{visite.heure}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Rappel : visite demain pour {{bien.titre}}" } },
  { id: "bailleur_bail_signe", label: "Bail signé", description: "Le bail est signé par le locataire", defaultRecipient: "both", clientType: "bailleur",
    agentTemplate: { emailObjet: "Bail signé - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nLe bail de location pour {{bien.titre}} a été signé.\\n\\nLocataire : {{locataire.prenom}} {{locataire.nom}}\\n\\nDate d'entrée : {{bail.date_entree}}\\n\\nLoyer : {{bail.loyer}} €\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Bail signé - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Bail signé - Location en cours", emailMessage: "Bonjour {{client.prenom}},\\n\\nLe bail de location pour {{bien.titre}} est signé avec {{locataire.prenom}} {{locataire.nom}}.\\n\\nEntrée en vigueur : {{bail.date_entree}}\\n\\nLoyer mensuel : {{bail.loyer}} €\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Bail signé pour {{bien.titre}}. Location en cours." } },
  { id: "bailleur_bail_expire_bientot", label: "Bail expire bientôt (J-30)", description: "30 jours avant la fin du bail", defaultRecipient: "both", clientType: "bailleur",
    agentTemplate: { emailObjet: "Bail expire bientôt - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nLe bail de {{bien.titre}} expire dans 30 jours.\\n\\nLocataire : {{locataire.prenom}} {{locataire.nom}}\\n\\nDate d'expiration : {{bail.date_expiration}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Bail expire J-30 - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Votre bail expire bientôt", emailMessage: "Bonjour {{client.prenom}},\\n\\nLe bail de {{bien.titre}} arrive à expiration dans 30 jours.\\n\\nSouhaitez-vous le renouveler ? Contactez-nous.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Bail expire dans 30 jours pour {{bien.titre}}." } },
  { id: "bailleur_locataire_sortant", label: "Locataire sortant (J-15)", description: "15 jours avant la fin du bail", defaultRecipient: "client", clientType: "bailleur",
    agentTemplate: { emailObjet: "Locataire sortant J-15 - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nLe locataire de {{bien.titre}} quitte le logement dans 15 jours.\\n\\nLocataire : {{locataire.prenom}} {{locataire.nom}}\\n\\nDate de sortie : {{bail.date_fin}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Sortie J-15 - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Préparation sortie locataire - {{bien.titre}}", emailMessage: "Bonjour {{client.prenom}},\\n\\nLe locataire quitte {{bien.titre}} dans 15 jours.\\n\\nNous préparons l'état des lieux de sortie et la remise en location.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Locataire sortant J-15 pour {{bien.titre}}" } },
  { id: "bailleur_loyers_impayes_j5", label: "Loyers impayés (J+5)", description: "Loyer impayé depuis 5 jours", defaultRecipient: "both", clientType: "bailleur",
    agentTemplate: { emailObjet: "Alerte impayé J+5 - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nLe loyer de {{bien.titre}} n'a pas été payé (J+5).\\n\\nLocataire : {{locataire.prenom}} {{locataire.nom}}\\n\\nMontant dû : {{loyer.montant}} €\\n\\nÉchéance : {{loyer.date_echeance}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Impayé J+5 - {{bien.titre}} - {{loyer.montant}}€" },
    clientTemplate: { emailObjet: "Alerte - Impayé de loyer", emailMessage: "Bonjour {{client.prenom}},\\n\\nNous vous informons que le loyer de {{bien.titre}} n'a pas été perçu à ce jour.\\n\\nNous mettons tout en œuvre pour régulariser la situation.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Impayé signalé pour {{bien.titre}}. Nous gérons la situation." } },
  { id: "bailleur_loyers_impayes_j15", label: "Loyers impayés (J+15)", description: "Loyer impayé depuis 15 jours", defaultRecipient: "agent", clientType: "bailleur",
    agentTemplate: { emailObjet: "Alerte impayé J+15 - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nLe loyer de {{bien.titre}} est impayé depuis 15 jours.\\n\\nLocataire : {{locataire.prenom}} {{locataire.nom}}\\n\\nMontant dû : {{loyer.montant}} €\\n\\nDes mesures doivent être prises.\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Impayé J+15 - {{bien.titre}} - Action requise" } },
  { id: "bailleur_demande_travaux", label: "Demande de travaux", description: "Le locataire signale un problème", defaultRecipient: "both", clientType: "bailleur",
    agentTemplate: { emailObjet: "Demande de travaux - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nLe locataire de {{bien.titre}} a signalé un problème.\\n\\nDescription : {{travaux.description}}\\n\\nPriorité : {{travaux.priorite}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Travaux signalés - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Demande de travaux - {{bien.titre}}", emailMessage: "Bonjour {{client.prenom}},\\n\\nUne demande de travaux a été signalée pour {{bien.titre}}.\\n\\nDescription : {{travaux.description}}\\n\\nNous vous tiendrons informé des suites.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Travaux pour {{bien.titre}}." } },
  { id: "bailleur_document_demande", label: "Document demandé au bailleur", description: "L'agent demande un document", defaultRecipient: "client", clientType: "bailleur",
    agentTemplate: { emailObjet: "Document demandé à {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nVous avez demandé un document à {{client.prenom}} {{client.nom}}.\\n\\nDocument : {{document.nom}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Document demandé à {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Document nécessaire pour {{bien.titre}}", emailMessage: "Bonjour {{client.prenom}},\\n\\nNous avons besoin du document suivant pour le dossier de {{bien.titre}} :\\n\\nDocument : {{document.nom}}\\n\\nMerci de nous le transmettre.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Document requis pour {{bien.titre}}" } },
  { id: "locataire_demande_location_creer", label: "Nouvelle demande de location créée", description: "Le locataire crée une demande de location", defaultRecipient: "both", clientType: "locataire",
    agentTemplate: { emailObjet: "Nouvelle demande location - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a créé une demande de location.\\n\\nCritères : {{demande.criteres}}\\n\\nBudget max : {{demande.budget_max}} €\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Demande location - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Confirmation de votre demande de location", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre demande de location a bien été enregistrée.\\n\\nNous recherchons le bien idéal pour vous.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Votre demande de location est bien prise en compte." } },
  { id: "locataire_demande_location_modifiee", label: "Demande de location modifiée", description: "Le locataire modifie ses critères", defaultRecipient: "both", clientType: "locataire",
    agentTemplate: { emailObjet: "Demande modifiée - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a modifié sa demande de location.\\n\\nNouveaux critères : {{demande.criteres}}\\n\\nBudget max : {{demande.budget_max}} €\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Demande modifiée - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Votre demande de location a été modifiée", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre demande de location a bien été mise à jour.\\n\\nNous affinons notre recherche avec vos nouveaux critères.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Votre demande de location a été mise à jour." } },
  { id: "locataire_croisement", label: "Nouveau croisement trouvé", description: "Un bien correspond aux critères du locataire", defaultRecipient: "both", clientType: "locataire",
    agentTemplate: { emailObjet: "Nouveau croisement - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nNouveau bien trouvé pour {{client.prenom}} {{client.nom}} :\\n\\n{{bien.titre}} - {{bien.prix}} €/mois\\n\\nCorrespondance : {{score}}%\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Nouveau bien pour {{client.prenom}} - {{score}}% correspondance" },
    clientTemplate: { emailObjet: "Un nouveau bien correspond à votre recherche", emailMessage: "Bonjour {{client.prenom}},\\n\\nNous avons trouvé un bien qui pourrait vous intéresser :\\n\\n{{bien.titre}} - {{bien.prix}} €/mois\\n\\nSurface : {{bien.surface}} m² · {{bien.pieces}} pièces\\n\\nVoir le bien : {{lien_client}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Nouveau bien : {{bien.titre}} - {{bien.prix}}€/mois. {{lien_client}}" } },
  { id: "locataire_proposition_consultee", label: "Proposition consultée", description: "Le locataire consulte une proposition", defaultRecipient: "agent", clientType: "locataire",
    agentTemplate: { emailObjet: "Proposition consultée - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a consulté la proposition :\\n\\nBien : {{bien.titre}} - {{bien.prix}} €\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "{{client.prenom}} {{client.nom}} a consulté {{bien.titre}}" } },
  { id: "locataire_proposition_sauvegardee", label: "Proposition sauvegardée", description: "Le locataire sauvegarde un bien", defaultRecipient: "agent", clientType: "locataire",
    agentTemplate: { emailObjet: "Bien sauvegardé - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a sauvegardé un bien :\\n\\n{{bien.titre}} - {{bien.prix}} €/mois\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Favori : {{bien.titre}} - {{client.prenom}} {{client.nom}}" } },
  { id: "locataire_demande_visite", label: "Demande de visite effectuée", description: "Le locataire demande une visite", defaultRecipient: "both", clientType: "locataire",
    agentTemplate: { emailObjet: "Demande de visite - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a demandé une visite pour {{bien.titre}}.\\n\\nDate souhaitée : {{visite.date}} à {{visite.heure}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Visite demandée - {{client.prenom}} {{client.nom}} - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Confirmation de votre demande de visite", emailMessage: "Bonjour {{client.prenom}},\\n\\nNous avons bien reçu votre demande de visite pour {{bien.titre}}.\\n\\nDate souhaitée : {{visite.date}} à {{visite.heure}}\\n\\nNous vous confirmerons le rendez-vous très prochainement.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Votre demande de visite pour {{bien.titre}} a été reçue." } },
  { id: "locataire_rappel_visite_24h", label: "Rappel de visite (24h avant)", description: "24h avant la date de visite", defaultRecipient: "client", clientType: "locataire",
    agentTemplate: { emailObjet: "Rappel visite 24h - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nRappel : {{client.prenom}} {{client.nom}} a une visite demain.\\n\\nBien : {{bien.titre}}\\n\\nDate : {{visite.date}} à {{visite.heure}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Rappel visite demain - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Rappel - Votre visite demain", emailMessage: "Bonjour {{client.prenom}},\\n\\nRappel : votre visite pour {{bien.titre}} est demain.\\n\\nDate : {{visite.date}} à {{visite.heure}}\\n\\nAdresse : {{bien.adresse}}\\n\\nÀ demain !\\n\\nL'équipe Square Meter", smsMessage: "Rappel : visite demain à {{visite.heure}} - {{bien.adresse}}" } },
  { id: "locataire_rappel_visite_1h", label: "Rappel de visite (1h avant)", description: "1h avant la date de visite", defaultRecipient: "client", clientType: "locataire",
    agentTemplate: { emailObjet: "Rappel visite 1h - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nRappel : {{client.prenom}} {{client.nom}} a une visite dans 1h.\\n\\nBien : {{bien.titre}}\\n\\nAdresse : {{bien.adresse}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Rappel visite 1h - {{bien.adresse}}" },
    clientTemplate: { emailObjet: "Rappel - Visite dans 1 heure", emailMessage: "Bonjour {{client.prenom}},\\n\\nRappel : votre visite pour {{bien.titre}} est dans 1 heure.\\n\\nAdresse : {{bien.adresse}}\\n\\nÀ très vite !\\n\\nL'équipe Square Meter", smsMessage: "Rappel : visite dans 1h - {{bien.adresse}}" } },
  { id: "locataire_dossier_complet", label: "Dossier de location complet", description: "Tous les documents du dossier sont reçus", defaultRecipient: "agent", clientType: "locataire",
    agentTemplate: { emailObjet: "Dossier complet - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLe dossier de location de {{client.prenom}} {{client.nom}} est complet.\\n\\nDocuments reçus : {{dossier.documents}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Dossier complet - {{client.prenom}} {{client.nom}}" } },
  { id: "locataire_bail_signe", label: "Bail signé", description: "Le bail est signé", defaultRecipient: "both", clientType: "locataire",
    agentTemplate: { emailObjet: "Bail signé - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLe bail a été signé avec {{client.prenom}} {{client.nom}}.\\n\\nBien : {{bien.titre}}\\n\\nDate d'entrée : {{bail.date_entree}}\\n\\nLoyer : {{bail.loyer}} €\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Bail signé - {{client.prenom}} {{client.nom}} - {{bien.titre}}" },
    clientTemplate: { emailObjet: "Bail signé - Bienvenue !", emailMessage: "Bonjour {{client.prenom}},\\n\\nFélicitations ! Votre bail pour {{bien.titre}} est signé.\\n\\nVous prendrez possession des lieux le {{bail.date_entree}}.\\n\\nBienvenue dans votre nouveau logement !\\n\\nL'équipe Square Meter", smsMessage: "Bail signé pour {{bien.titre}}. Entrée le {{bail.date_entree}}" } },
  { id: "locataire_bail_expire_bientot", label: "Bail expire bientôt (J-30)", description: "30 jours avant la fin du bail", defaultRecipient: "client", clientType: "locataire",
    agentTemplate: { emailObjet: "Bail expire J-30 - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLe bail de {{client.prenom}} {{client.nom}} expire dans 30 jours.\\n\\nBien : {{bien.titre}}\\n\\nDate d'expiration : {{bail.date_expiration}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Bail expire J-30 - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Votre bail expire bientôt", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre bail pour {{bien.titre}} arrive à expiration dans 30 jours.\\n\\nSouhaitez-vous le renouveler ? Contactez-nous.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Votre bail expire dans 30 jours." } },
  { id: "locataire_document_ajoute", label: "Document ajouté par le locataire", description: "Le locataire uploade un document", defaultRecipient: "agent", clientType: "locataire",
    agentTemplate: { emailObjet: "Document ajouté - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a ajouté un document.\\n\\nDocument : {{document.nom}}\\n\\nType : {{document.type}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Document ajouté par {{client.prenom}} {{client.nom}}" } },
  { id: "voyageur_reservation_option", label: "Nouvelle réservation (option)", description: "Une réservation est créée en option", defaultRecipient: "both", clientType: "voyageur",
    agentTemplate: { emailObjet: "Réservation en option - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a créé une réservation en option.\\n\\nBien : {{bien.titre}}\\n\\nArrivée : {{sejour.date_arrivee}}\\n\\nDépart : {{sejour.date_depart}}\\n\\nMontant : {{reservation.montant}} €\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Réservation option - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Votre réservation en option - {{bien.titre}}", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre réservation pour {{bien.titre}} est en option.\\n\\nArrivée : {{sejour.date_arrivee}}\\n\\nDépart : {{sejour.date_depart}}\\n\\nCette option expire dans 48h. Confirmez-la dès que possible.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Réservation option pour {{bien.titre}}. Confirmez dans 48h." } },
  { id: "voyageur_reservation_confirmee", label: "Réservation confirmée", description: "La réservation passe en confirmée", defaultRecipient: "both", clientType: "voyageur",
    agentTemplate: { emailObjet: "Réservation confirmée - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nRéservation confirmée pour {{client.prenom}} {{client.nom}}.\\n\\nBien : {{bien.titre}}\\n\\nArrivée : {{sejour.date_arrivee}}\\n\\nDépart : {{sejour.date_depart}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Réservation confirmée - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Réservation confirmée - {{bien.titre}}", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre réservation pour {{bien.titre}} est confirmée !\\n\\nArrivée : {{sejour.date_arrivee}}\\n\\nDépart : {{sejour.date_depart}}\\n\\nNous vous préparons un accueil personnalisé.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Réservation confirmée pour {{bien.titre}} !" } },
  { id: "voyageur_reservation_annulee", label: "Réservation annulée", description: "La réservation est annulée", defaultRecipient: "agent", clientType: "voyageur",
    agentTemplate: { emailObjet: "Réservation annulée - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a annulé sa réservation.\\n\\nBien : {{bien.titre}}\\n\\nAnnulation le : {{annulation.date}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Réservation annulée - {{client.prenom}} {{client.nom}}" } },
  { id: "voyageur_rappel_sejour_7j", label: "Rappel séjour (J-7)", description: "7 jours avant l'arrivée", defaultRecipient: "client", clientType: "voyageur",
    agentTemplate: { emailObjet: "Rappel séjour J-7 - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nRappel : le séjour de {{client.prenom}} {{client.nom}} commence dans 7 jours.\\n\\nBien : {{bien.titre}}\\n\\nArrivée : {{sejour.date_arrivee}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Séjour J-7 - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Votre séjour approche (J-7)", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre séjour à {{bien.titre}} commence dans une semaine !\\n\\nArrivée : {{sejour.date_arrivee}}\\n\\nDépart : {{sejour.date_depart}}\\n\\nDes questions ? Contactez-nous.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Plus que 7 jours avant votre séjour à {{bien.titre}} !" } },
  { id: "voyageur_rappel_sejour_1j", label: "Rappel séjour (J-1)", description: "1 jour avant l'arrivée", defaultRecipient: "client", clientType: "voyageur",
    agentTemplate: { emailObjet: "Rappel séjour J-1 - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nRappel : le séjour de {{client.prenom}} {{client.nom}} commence demain.\\n\\nBien : {{bien.titre}}\\n\\nArrivée : {{sejour.date_arrivee}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Séjour J-1 - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Votre séjour commence demain !", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre séjour à {{bien.titre}} commence demain !\\n\\nArrivée : {{sejour.date_arrivee}}\\n\\nAdresse : {{bien.adresse}}\\n\\nProfitez bien de votre séjour !\\n\\nL'équipe Square Meter", smsMessage: "Votre séjour à {{bien.titre}} commence demain !" } },
  { id: "voyageur_checkin_guide", label: "Check-in guide envoyé", description: "Le guide d'arrivée est envoyé", defaultRecipient: "client", clientType: "voyageur",
    agentTemplate: { emailObjet: "Guide d'arrivée envoyé - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLe guide d'arrivée a été envoyé à {{client.prenom}} {{client.nom}}.\\n\\nBien : {{bien.titre}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Guide envoyé - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Votre guide d'arrivée - {{bien.titre}}", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre guide d'arrivée pour {{bien.titre}} est disponible.\\n\\nAccès au logement : {{guide.acces}}\\n\\nBonnes adresses : {{guide.bonnes_adresses}}\\n\\nBon séjour !\\n\\nL'équipe Square Meter", smsMessage: "Guide d'arrivée disponible pour {{bien.titre}}." } },
  { id: "voyageur_sejour_en_cours", label: "Séjour en cours", description: "Le jour de l'arrivée", defaultRecipient: "client", clientType: "voyageur",
    agentTemplate: { emailObjet: "Séjour en cours - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLe séjour de {{client.prenom}} {{client.nom}} commence aujourd'hui.\\n\\nBien : {{bien.titre}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Séjour en cours - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Bienvenue - Début de votre séjour !", emailMessage: "Bonjour {{client.prenom}},\\n\\nBienvenue ! Votre séjour à {{bien.titre}} commence aujourd'hui.\\n\\nNous espérons que vous passerez un excellent moment.\\n\\nBesoin de quelque chose ? Contactez-nous.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Bienvenue à {{bien.titre}} ! Bon séjour !" } },
  { id: "voyageur_fin_sejour", label: "Fin du séjour (J+1)", description: "1 jour après le départ", defaultRecipient: "client", clientType: "voyageur",
    agentTemplate: { emailObjet: "Fin séjour J+1 - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLe séjour de {{client.prenom}} {{client.nom}} s'est terminé hier.\\n\\nBien : {{bien.titre}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Fin séjour - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Nous espérons que vous avez passé un bon séjour", emailMessage: "Bonjour {{client.prenom}},\\n\\nNous espérons que votre séjour à {{bien.titre}} s’est bien passé.\\n\\nVotre avis nous intéresse !\\n\\nÀ bientôt,\\n\\nL'équipe Square Meter", smsMessage: "Bon séjour chez nous ? Donnez votre avis !" } },
  { id: "voyageur_demande_avis", label: "Demande d'avis", description: "3 jours après le départ", defaultRecipient: "client", clientType: "voyageur",
    agentTemplate: { emailObjet: "Demande d'avis - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nDemande d'avis pour le séjour de {{client.prenom}} {{client.nom}}.\\n\\nBien : {{bien.titre}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Avis demandé - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Donnez votre avis sur votre séjour", emailMessage: "Bonjour {{client.prenom}},\\n\\nComment s’est passé votre séjour à {{bien.titre}} ?\\n\\nVotre avis est précieux pour nous aider à améliorer nos services.\\n\\nDonner mon avis : {{lien_avis}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Donnez votre avis sur {{bien.titre}} : {{lien_avis}}" } },
  { id: "voyageur_avis_laisse", label: "Avis laissé", description: "Le voyageur laisse un avis", defaultRecipient: "agent", clientType: "voyageur",
    agentTemplate: { emailObjet: "Avis laissé - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a laissé un avis.\\n\\nBien : {{bien.titre}}\\n\\nNote : {{avis.note}}/5\\n\\nCommentaire : {{avis.commentaire}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Avis de {{avis.note}}/5 laissé par {{client.prenom}} {{client.nom}}" } },
  { id: "voyageur_message_recu", label: "Message reçu du voyageur", description: "Le voyageur envoie un message", defaultRecipient: "both", clientType: "voyageur",
    agentTemplate: { emailObjet: "Message de {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} vous a envoyé un message.\\n\\nMessage : {{message.contenu}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Message de {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Votre message a bien été envoyé", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre message a bien été transmis à notre équipe.\\n\\nNous vous répondrons dans les plus brefs délais.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Message envoyé. Nous vous répondons rapidement." } },
  { id: "voyageur_document_ajoute", label: "Document ajouté par le voyageur", description: "Le voyageur uploade un document", defaultRecipient: "agent", clientType: "voyageur",
    agentTemplate: { emailObjet: "Document ajouté - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} a ajouté un document.\\n\\nDocument : {{document.nom}}\\n\\nType : {{document.type}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Document ajouté par {{client.prenom}} {{client.nom}}" } },
  { id: "contact_anniversaire", label: "Anniversaire du contact", description: "Le jour de l'anniversaire du contact", defaultRecipient: "client", clientType: "contacts",
    agentTemplate: { emailObjet: "Anniversaire - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nC'est l'anniversaire de {{client.prenom}} {{client.nom}} aujourd'hui !\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Joyeux anniversaire {{client.prenom}} {{client.nom}} !" },
    clientTemplate: { emailObjet: "Joyeux anniversaire {{client.prenom}} !", emailMessage: "Bonjour {{client.prenom}},\\n\\nToute l'équipe Square Meter vous souhaite un merveilleux anniversaire !\\n\\nNous sommes heureux de vous compter parmi nos clients.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Joyeux anniversaire {{client.prenom}} ! - Square Meter" } },
  { id: "contact_anniversaire_j3", label: "Anniversaire (J-3)", description: "3 jours avant l'anniversaire", defaultRecipient: "agent", clientType: "contacts",
    agentTemplate: { emailObjet: "Anniversaire J-3 - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} fête son anniversaire dans 3 jours !\\n\\nPensez à préparer un message personnalisé.\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Anniversaire J-3 - {{client.prenom}} {{client.nom}}" } },
  { id: "contact_inactivite_extranet_30j", label: "Inactivité Squaremeter (J+30)", description: "30 jours sans connexion au Squaremeter", defaultRecipient: "client", clientType: "contacts",
    agentTemplate: { emailObjet: "Inactivité Squaremeter 30j - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} ne s'est pas connecté au Squaremeter depuis 30 jours.\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Inactivité Squaremeter 30j - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Votre espace Squaremeter vous attend", emailMessage: "Bonjour {{client.prenom}},\\n\\nCela fait 30 jours que vous ne vous êtes pas connecté à votre espace Squaremeter.\\n\\nConnectez-vous pour consulter vos documents :\\n\\n{{lien_client}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Reconnectez-vous à votre Squaremeter : {{lien_client}}" } },
  { id: "contact_inactivite_extranet_60j", label: "Inactivité Squaremeter (J+60)", description: "60 jours sans connexion au Squaremeter", defaultRecipient: "agent", clientType: "contacts",
    agentTemplate: { emailObjet: "Inactivité Squaremeter 60j - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} ne s'est pas connecté au Squaremeter depuis 60 jours.\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Inactivité Squaremeter 60j - {{client.prenom}} {{client.nom}}" } },
  { id: "contact_document_expirant", label: "Document expirant (J-30)", description: "30 jours avant l'expiration d'un document", defaultRecipient: "client", clientType: "contacts",
    agentTemplate: { emailObjet: "Document expire J-30 - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nUn document de {{client.prenom}} {{client.nom}} expire dans 30 jours.\\n\\nDocument : {{document.nom}}\\n\\nDate d'expiration : {{document.date_expiration}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Document expire J-30 - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Votre document expire bientôt", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre document {{document.nom}} expire dans 30 jours.\\n\\nMerci de nous fournir un document à jour.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Document {{document.nom}} expire dans 30 jours." } },
  { id: "contact_newsletter_mensuelle", label: "Newsletter mensuelle", description: "Le 1er du mois", defaultRecipient: "client", clientType: "contacts",
    agentTemplate: { emailObjet: "Newsletter mensuelle envoyée", emailMessage: "Bonjour,\\n\\nLa newsletter mensuelle a été envoyée aux contacts.\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Newsletter mensuelle envoyée" },
    clientTemplate: { emailObjet: "Newsletter Square Meter - {{mois}}", emailMessage: "Bonjour {{client.prenom}},\\n\\nDécouvrez les dernières actualités et les nouveaux biens du mois.\\n\\n{{contenu_newsletter}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Newsletter Square Meter - {{mois}}. Découvrez nos actualités." } },
  { id: "calendrier_nouveau_rdv", label: "Nouveau rendez-vous créé", description: "Un rendez-vous est ajouté au calendrier", defaultRecipient: "both", clientType: "calendrier",
    agentTemplate: { emailObjet: "Nouveau rendez-vous - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nUn nouveau rendez-vous a été créé avec {{client.prenom}} {{client.nom}}.\\n\\nSujet : {{rdv.sujet}}\\n\\nDate : {{rdv.date}} à {{rdv.heure}}\\n\\nAdresse : {{rdv.adresse}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Nouveau RDV - {{client.prenom}} {{client.nom}} le {{rdv.date}}" },
    clientTemplate: { emailObjet: "Confirmation de votre rendez-vous", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre rendez-vous a été confirmé :\\n\\nSujet : {{rdv.sujet}}\\n\\nDate : {{rdv.date}} à {{rdv.heure}}\\n\\nAdresse : {{rdv.adresse}}\\n\\nÀ bientôt !\\n\\nL'équipe Square Meter", smsMessage: "RDV confirmé le {{rdv.date}} à {{rdv.heure}} - {{rdv.adresse}}" } },
  { id: "calendrier_rappel_24h", label: "Rappel de rendez-vous (24h avant)", description: "24h avant le rendez-vous", defaultRecipient: "both", clientType: "calendrier",
    agentTemplate: { emailObjet: "Rappel RDV 24h - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nRappel : Rendez-vous demain avec {{client.prenom}} {{client.nom}}.\\n\\nSujet : {{rdv.sujet}}\\n\\nDate : {{rdv.date}} à {{rdv.heure}}\\n\\nAdresse : {{rdv.adresse}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Rappel RDV demain {{rdv.heure}} - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Rappel - Votre rendez-vous demain", emailMessage: "Bonjour {{client.prenom}},\\n\\nRappel de votre rendez-vous de demain :\\n\\nDate : {{rdv.date}} à {{rdv.heure}}\\n\\nAdresse : {{rdv.adresse}}\\n\\nÀ demain !\\n\\nL'équipe Square Meter", smsMessage: "Rappel RDV demain à {{rdv.heure}} - {{rdv.adresse}}" } },
  { id: "calendrier_rappel_1h", label: "Rappel de rendez-vous (1h avant)", description: "1h avant le rendez-vous", defaultRecipient: "both", clientType: "calendrier",
    agentTemplate: { emailObjet: "Rappel RDV 1h - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nRappel : Rendez-vous dans 1 heure avec {{client.prenom}} {{client.nom}}.\\n\\nSujet : {{rdv.sujet}}\\n\\nAdresse : {{rdv.adresse}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Rappel RDV 1h - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Rappel - Votre rendez-vous dans 1 heure", emailMessage: "Bonjour {{client.prenom}},\\n\\nRappel : votre rendez-vous est dans 1 heure.\\n\\nAdresse : {{rdv.adresse}}\\n\\nÀ très vite !\\n\\nL'équipe Square Meter", smsMessage: "Rappel RDV 1h - {{rdv.adresse}}" } },
  { id: "calendrier_rdv_modifie", label: "Rendez-vous modifié", description: "Le rendez-vous est modifié", defaultRecipient: "both", clientType: "calendrier",
    agentTemplate: { emailObjet: "RDV modifié - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLe rendez-vous avec {{client.prenom}} {{client.nom}} a été modifié.\\n\\nSujet : {{rdv.sujet}}\\n\\nNouvelle date : {{rdv.date}} à {{rdv.heure}}\\n\\nAdresse : {{rdv.adresse}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "RDV modifié - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Votre rendez-vous a été modifié", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre rendez-vous a été mis à jour :\\n\\nNouvelle date : {{rdv.date}} à {{rdv.heure}}\\n\\nAdresse : {{rdv.adresse}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "RDV modifié : {{rdv.date}} à {{rdv.heure}}" } },
  { id: "contrat_vente_signe", label: "Contrat de vente signé", description: "Signature du contrat de vente", defaultRecipient: "both", clientType: "contrats",
    agentTemplate: { emailObjet: "Contrat de vente signé - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLe contrat de vente a été signé par {{client.prenom}} {{client.nom}}.\\n\\nBien : {{bien.titre}}\\n\\nMontant : {{bien.prix}} €\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Contrat vente signé - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Contrat de vente signé - Félicitations !", emailMessage: "Bonjour {{client.prenom}},\\n\\nFélicitations ! Le contrat de vente pour {{bien.titre}} est signé.\\n\\nNous vous accompagnons jusqu'à la finalisation.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Contrat de vente signé pour {{bien.titre}}. Félicitations !" } },
  { id: "contrat_location_signe", label: "Contrat de location signé", description: "Signature du bail de location", defaultRecipient: "both", clientType: "contrats",
    agentTemplate: { emailObjet: "Contrat location signé - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLe contrat de location a été signé par {{client.prenom}} {{client.nom}}.\\n\\nBien : {{bien.titre}}\\n\\nLoyer : {{bail.loyer}} €\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Contrat location signé - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Contrat de location signé", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre contrat de location pour {{bien.titre}} est signé.\\n\\nEntrée en vigueur : {{bail.date_entree}}\\n\\nBienvenue dans votre nouveau logement !\\n\\nL'équipe Square Meter", smsMessage: "Contrat de location signé pour {{bien.titre}}." } },
  { id: "contrat_saisonnier_signe", label: "Contrat saisonnier signé", description: "Signature du contrat saisonnier", defaultRecipient: "both", clientType: "contrats",
    agentTemplate: { emailObjet: "Contrat saisonnier signé - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLe contrat saisonnier a été signé par {{client.prenom}} {{client.nom}}.\\n\\nBien : {{bien.titre}}\\n\\nType : {{contrat.type}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Contrat saisonnier signé - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Contrat saisonnier signé - {{bien.titre}}", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre contrat saisonnier pour {{bien.titre}} est signé.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Contrat saisonnier signé pour {{bien.titre}}." } },
  { id: "contrat_fin_periode_reflexion_j1", label: "Fin période de réflexion (J-1)", description: "1 jour avant la fin du délai légal", defaultRecipient: "both", clientType: "contrats",
    agentTemplate: { emailObjet: "Fin période réflexion J-1 - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLa période de réflexion pour le contrat de {{client.prenom}} {{client.nom}} se termine demain.\\n\\nBien : {{bien.titre}}\\n\\nDate limite : {{contrat.date_limite}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Période réflexion J-1 - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Fin de votre période de réflexion demain", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre période de réflexion pour {{bien.titre}} se termine demain.\\n\\nN'hésitez pas à nous contacter si vous avez des questions.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Période réflexion expire demain pour {{bien.titre}}." } },
  { id: "contrat_fin_periode_reflexion_j0", label: "Fin période de réflexion (J-0)", description: "Le jour de la fin du délai légal", defaultRecipient: "agent", clientType: "contrats",
    agentTemplate: { emailObjet: "Fin période réflexion - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLa période de réflexion pour {{client.prenom}} {{client.nom}} se termine aujourd'hui.\\n\\nBien : {{bien.titre}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Fin période réflexion - {{client.prenom}} {{client.nom}}" } },
  { id: "contrat_termine", label: "Contrat terminé", description: "Le contrat est finalisé", defaultRecipient: "agent", clientType: "contrats",
    agentTemplate: { emailObjet: "Contrat terminé - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLe contrat de {{client.prenom}} {{client.nom}} est terminé.\\n\\nBien : {{bien.titre}}\\n\\nType : {{contrat.type}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Contrat terminé - {{client.prenom}} {{client.nom}}" } },
  { id: "extranet_nouvelle_action", label: "Nouvelle action Squaremeter", description: "Un document est ajouté dans l'espace client", defaultRecipient: "client", clientType: "extranet",
    agentTemplate: { emailObjet: "Action Squaremeter - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nUne nouvelle action a été effectuée sur le Squaremeter de {{client.prenom}} {{client.nom}}.\\n\\nType : {{extranet.action_type}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Action Squaremeter - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Nouveau document dans votre espace Squaremeter", emailMessage: "Bonjour {{client.prenom}},\\n\\nUn nouveau document a été ajouté à votre espace Squaremeter.\\n\\nConnectez-vous pour le consulter :\\n\\n{{lien_client}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Nouveau document disponible sur votre Squaremeter. {{lien_client}}" } },
  { id: "extranet_identifiants", label: "Identifiants Squaremeter envoyés", description: "Envoi des identifiants de connexion", defaultRecipient: "client", clientType: "extranet",
    agentTemplate: { emailObjet: "Identifiants Squaremeter envoyés - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLes identifiants Squaremeter ont été envoyés à {{client.prenom}} {{client.nom}}.\\n\\nEmail : {{client.email}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Identifiants envoyés - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Bienvenue sur votre espace Squaremeter", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre espace Squaremeter a été créé.\\n\\nEmail : {{client.email}}\\n\\nLien de connexion : {{lien_client}}\\n\\nConnectez-vous pour accéder à tous vos documents.\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Bienvenue sur votre Squaremeter : {{lien_client}}" } },
  { id: "extranet_mdp_reinitialise", label: "Mot de passe Squaremeter réinitialisé", description: "Réinitialisation du mot de passe Squaremeter", defaultRecipient: "client", clientType: "extranet",
    agentTemplate: { emailObjet: "Mot de passe réinitialisé - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nLe mot de passe Squaremeter de {{client.prenom}} {{client.nom}} a été réinitialisé.\\n\\nEmail : {{client.email}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "MDP réinitialisé - {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Votre mot de passe Squaremeter a été réinitialisé", emailMessage: "Bonjour {{client.prenom}},\\n\\nVotre mot de passe Squaremeter a été réinitialisé.\\n\\nConnectez-vous avec votre nouveau mot de passe :\\n\\n{{lien_client}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Mot de passe réinitialisé. Connectez-vous : {{lien_client}}" } },
  { id: "extranet_client_connecte", label: "Client se connecte au Squaremeter", description: "Première connexion au Squaremeter", defaultRecipient: "agent", clientType: "extranet",
    agentTemplate: { emailObjet: "Connexion Squaremeter - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} s'est connecté à son espace Squaremeter pour la première fois.\\n\\nDate : {{connexion.date}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "{{client.prenom}} {{client.nom}} connecté au Squaremeter" } },
  { id: "extranet_connexion_apres_30j", label: "Connexion Squaremeter (après 30j)", description: "Connexion après 30 jours d'inactivité", defaultRecipient: "agent", clientType: "extranet",
    agentTemplate: { emailObjet: "Connexion après 30j - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\n{{client.prenom}} {{client.nom}} s'est reconnecté au Squaremeter après 30 jours d'inactivité.\\n\\nDate : {{connexion.date}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Reconnexion Squaremeter - {{client.prenom}} {{client.nom}}" } },
  { id: "extranet_document_ajoute_agent", label: "Nouveau document ajouté par l'agent", description: "Document ajouté dans l'espace client", defaultRecipient: "client", clientType: "extranet",
    agentTemplate: { emailObjet: "Document ajouté par l'agent - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nUn document a été ajouté dans l'espace Squaremeter de {{client.prenom}} {{client.nom}}.\\n\\nDocument : {{document.nom}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Document ajouté pour {{client.prenom}} {{client.nom}}" },
    clientTemplate: { emailObjet: "Nouveau document dans votre espace", emailMessage: "Bonjour {{client.prenom}},\\n\\nUn nouveau document a été ajouté à votre espace Squaremeter.\\n\\nDocument : {{document.nom}}\\n\\nConsultez-le : {{lien_client}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Nouveau document disponible : {{lien_client}}" } },
  { id: "admin_agent_inactif_30j", label: "Agent inactif (30j)", description: "Un agent ne s'est pas connecté depuis 30j", defaultRecipient: "agent", clientType: "admin",
    agentTemplate: { emailObjet: "Agent inactif 30j - {{agent.prenom}} {{agent.nom}}", emailMessage: "Bonjour,\\n\\nL'agent {{agent.prenom}} {{agent.nom}} ne s'est pas connecté depuis 30 jours.\\n\\nEmail : {{agent.email}}\\n\\nDernière connexion : {{agent.derniere_connexion}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Agent inactif 30j - {{agent.prenom}} {{agent.nom}}" } },
  { id: "admin_agent_inactif_60j", label: "Agent inactif (60j)", description: "Un agent ne s'est pas connecté depuis 60j", defaultRecipient: "agent", clientType: "admin",
    agentTemplate: { emailObjet: "Agent inactif 60j - {{agent.prenom}} {{agent.nom}}", emailMessage: "Bonjour,\\n\\nL'agent {{agent.prenom}} {{agent.nom}} ne s'est pas connecté depuis 60 jours.\\n\\nEmail : {{agent.email}}\\n\\nDernière connexion : {{agent.derniere_connexion}}\\n\\nDes mesures doivent être envisagées.\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Agent inactif 60j - {{agent.prenom}} {{agent.nom}}" } },
  { id: "admin_nouvel_utilisateur_inscrit", label: "Nouvel utilisateur inscrit (web app)", description: "Un nouveau client s'inscrit sur la web app", defaultRecipient: "agent", clientType: "admin",
    agentTemplate: { emailObjet: "Nouvel inscrit - {{client.prenom}} {{client.nom}}", emailMessage: "Bonjour,\\n\\nUn nouveau client s'est inscrit sur la web app :\\n\\nNom : {{client.prenom}} {{client.nom}}\\n\\nEmail : {{client.email}}\\n\\nTéléphone : {{client.telephone}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Nouvel inscrit : {{client.prenom}} {{client.nom}}" } },
  { id: "admin_nouvelle_propriete_ajoutee", label: "Nouvelle propriété ajoutée", description: "Un nouveau bien est ajouté dans le CRM", defaultRecipient: "agent", clientType: "admin",
    agentTemplate: { emailObjet: "Nouveau bien ajouté - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nUn nouveau bien a été ajouté dans le CRM par {{createur.prenom}} {{createur.nom}} ({{createur.role}}) :\\n\\nTitre : {{bien.titre}}\\n\\nType : {{bien.type}}\\n\\nPrix : {{bien.prix}}\\n\\nSurface : {{bien.surface}}\\n\\nVille : {{bien.ville}}\\n\\nAgent : {{agent.prenom}} {{agent.nom}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Nouveau bien : {{bien.titre}} - {{bien.prix}}" } },
  { id: "admin_propriete_vendue", label: "Propriété vendue", description: "Un bien est marqué \"Vendu\"", defaultRecipient: "agent", clientType: "admin",
    agentTemplate: { emailObjet: "Bien vendu - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nLe bien {{bien.titre}} a été marqué comme vendu.\\n\\nPrix de vente : {{bien.prix_vente}} €\\n\\nDate de vente : {{bien.date_vente}}\\n\\nAgent : {{agent.prenom}} {{agent.nom}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Vendu - {{bien.titre}} - {{bien.prix_vente}}€" } },
  { id: "admin_propriete_louee", label: "Propriété louée", description: "Un bien est marqué \"Loué\"", defaultRecipient: "agent", clientType: "admin",
    agentTemplate: { emailObjet: "Bien loué - {{bien.titre}}", emailMessage: "Bonjour,\\n\\nLe bien {{bien.titre}} a été marqué comme loué.\\n\\nLoyer : {{bien.loyer}} €/mois\\n\\nDate de location : {{bien.date_location}}\\n\\nAgent : {{agent.prenom}} {{agent.nom}}\\n\\nLien : {{lien_agent}}\\n\\nCordialement,\\n\\nL'équipe Square Meter", smsMessage: "Loué - {{bien.titre}} - {{bien.loyer}}€/mois" } },

];
